### ISSUE TITLE
Troubles installing 

### ISSUE THREAD

**Issue by troopertate** [jamsinclair/opifancontrol#5]
Hey I am on an orange pi 5 plus and on the OS Ubuntu. when running the install script it says it cant access a directory and when i run the enable command it says the opifancontrol.service does not exist. should i make all the directories and paste the stuff there and try again or is this not made for Ubuntu.

**Comment by jamsinclair** [comment]
Hey @troopertate, I saw you closed this. Were you able to resolve the issue?

If not, it'd be super helpful if you could also share the exact error logs so I can better help and improve the script! I currently am running this on a debian-based distro ([dietpi](https://dietpi.com/)) so I'd assume it should also work just fine with Ubuntu 🤔

**Comment by troopertate** [comment]
Hey thanks for making sure all is well, id like to apologize for how long it has taken me to respond. I didnt have a way to correctly connect the wire to the pwm pin and wanted to wait to reply to your message when i have an answer for you. it is working well! And i only have one question, how do i show the debug info, i set the setting to true in the file and im not sure what it is exactly supposed to come up with, im a bit new to orange pi/Ubuntu. thanks again!!

**Comment by jamsinclair** [comment]
No worries at all @troopertate! 😊 This is free software, there's no obligation to reply – life and things can easily get in the way.

You can update the config file with your editor of choice (vim, nano etc.) 
1. `nano /etc/opifancontrol.conf`
2. Add the line `DEBUG=true` or update the existing line to match.

Then to see the debugging information you print out the logs with `journalctl`
1. `journalctl -u opifancontrol`

This will output information on the current settings and changes to fan speed.

I'll add this note to the README about how to configure debugging.

**Comment by xsetiadi** [comment]
this not only work with 5v fan? i guess this the reason why my 12v fan not working. can you help me?
