### ISSUE TITLE
OPI5 Plus image shows the wrong pin for PWM....

### ISSUE THREAD

**Issue by RevBaker** [jamsinclair/opifancontrol#7]
GPIO READALL shows PWM at physical pin 7 , not 5 as shown in your image for PI5 PLUS.

Thanks for the code!!!

**Comment by jamsinclair** [comment]
Thanks @RevBaker. I believe there's multiple PWM pins available. I'm unsure which pin is best suited for running a fan, but I have been using physical pin 5 successfully for almost a year now. If physical pin 7 also works, that's great to know. 

You can find a complete pin layout at pages 224 and 225 in the user manual (https://orangepi.net/wp-content/uploads/2023/07/OrangePi_5_Plus_RK3588_user-manual_v1.5.1.pdf)

**Comment by RevBaker** [comment]
Yes there is......my mistake was relying only on the output of the GPIO READALL output. 5 shows PWM0_M0 and 7 shows PWM14_M2 on the link below. Always something more to learn. Thanks!


<https://www.google.com/search?q=orange%20pi%205%20plus%20gpio%20pinout&ie=utf-8&oe=utf-8&client=firefox-b-1-m#vhid=GSCk6c7brTHfIM&vssid=_GYdQZ5CQK-qgkPIPgfamyQQ_25>

**Comment by RevBaker** [comment]
However .....default opifancontrol.conf has FAN_GPIO_PIN=2 as does the .sh file and that stays the same for either the OPI5 or the OPI5 PLUS and that equates to physical pin 7.....but only the image of the OPI5 shows using physical pin 7  and the OPI5 PLUS shows using physical pin 5 (wPi 1). 

Pin 5 can be used because you can declare (wPi 1) to be PWM but if you don't it remains SCL.2 which is Synchronous Clock Line, a key component of the Inter-Integrated Circuit (I2C) bus protocol. In this context, SCL.2 refers to the second I2C clock line (SCL) on the OPI 5 and OPI 5 PLUS board.

I think the bottom line is the OPI5 image is correct in the use of physical pin 7 for the code as written but would do nothing for the OPI5 PLUS on physical pin 5 because the code never changes its default setting of SCL.2 on the 5 Plus.

At any rate, thanks for making me think about how the GPIO works as I'd never used it before and this was simple enough to wrap my head around and find the tools to work through it.

Noticed that your profile says you're in Japan.....my wife and I were both Air Traffic Controllers at Yokota AB in the late 70s.

Cheers!

No reply required. 👍
